package com.brcraft131313.cmdmakerformcpe0143;

import android.app.Activity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import java.io.File;
import java.io.FileOutputStream;

public class MainActivity extends Activity {

    private EditText commandNameInput, messageInput, functionInput;
    private Button exportButton;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        commandNameInput = (EditText) findViewById(R.id.commandNameInput);
        messageInput = (EditText) findViewById(R.id.messageInput);
        functionInput = (EditText) findViewById(R.id.functionInput);
        exportButton = (Button) findViewById(R.id.exportButton);

        exportButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                exportModScript();
            }
        });
    }

    private void exportModScript() {
        String cmdName = commandNameInput.getText().toString().trim();
        String msgText = messageInput.getText().toString().trim();
        String funcBody = functionInput.getText().toString().trim();

        if (cmdName.isEmpty()) {
            Toast.makeText(this, "الرجاء إدخال اسم الأمر", Toast.LENGTH_SHORT).show();
            return;
        }

        StringBuilder modCode = new StringBuilder();
        modCode.append("// ModPE 0.14.3 Script\n");
        modCode.append("// Generated by CmdMaker For MCPE 0.14.3\n\n");
        
        modCode.append("function procCmd(cmd) {\n");
        modCode.append("    var parts = cmd.split(\" \");\n");
        modCode.append("    if(parts[0] == \"").append(cmdName).append("\") {\n");
        modCode.append("        preventDefault();\n");
        
        if (!funcBody.isEmpty()) {
            modCode.append("        ").append(funcBody.replace("\n", "\n        ")).append("\n");
        }
        
        if (!msgText.isEmpty()) {
            modCode.append("        clientMessage(\"").append(msgText).append("\");\n");
        }
        
        modCode.append("    }\n");
        modCode.append("}\n");

        try {
            File dir = new File(getExternalFilesDir(null), "mods");
            if (!dir.exists()) {
                dir.mkdirs();
            }
            File file = new File(dir, cmdName + "_mod.js");
            FileOutputStream fos = new FileOutputStream(file);
            fos.write(modCode.toString().getBytes());
            fos.close();

            Toast.makeText(this, "تم التصدير بنجاح إلى: " + file.getAbsolutePath(), Toast.LENGTH_LONG).show();
        } catch (Exception e) {
            Toast.makeText(this, "خطأ أثناء التصدير: " + e.getMessage(), Toast.LENGTH_LONG).show();
        }
    }
}
